name: Quality assurance

on:
    pull_request:
        branches: [ main ]

jobs:
    static-analysis:
        runs-on: ubuntu-24.04
        name: Static analysis

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.4

            -   name: Install dependencies
                run: composer install --no-interaction --no-progress --ansi

            -   name: Psalm
                run: vendor/bin/psalm

    code-style:
        runs-on: ubuntu-24.04
        name: Code style

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup PHP

                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.4

            -   name: Install dependencies
                run: composer install --no-interaction --no-progress --ansi

            -   name: PHP-CS-Fixer
                run: PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --dry-run

    tests:
        runs-on: ubuntu-24.04
        strategy:
            max-parallel: 1
            matrix:
                php:
                    - 8.3
                    - 8.4
                include:
                    -   description: 8.3
                        php: 8.3
                    -   description: 8.4
                        php: 8.4

        name: Tests PHP ${{ matrix.php }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Cache
                uses: actions/cache@v4
                with:
                    path: ~/.composer/cache/files
                    key: ${{ matrix.php }}-${{ matrix.composer_option }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   name: Install dependencies
                run: composer install --no-interaction --no-progress --ansi

            -   name: Execute PHPUnit
                run: vendor/bin/phpunit
